/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LabRouteImport } from './routes/lab'
import { Route as CaseFilesRouteImport } from './routes/case-files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiHonoSplatRouteImport } from './routes/api/hono/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseFilesRoute = CaseFilesRouteImport.update({
  id: '/case-files',
  path: '/case-files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHonoSplatRoute = ApiHonoSplatRouteImport.update({
  id: '/api/hono/$',
  path: '/api/hono/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-files': typeof CaseFilesRoute
  '/lab': typeof LabRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/api/hono/$': typeof ApiHonoSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-files': typeof CaseFilesRoute
  '/lab': typeof LabRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/api/hono/$': typeof ApiHonoSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-files': typeof CaseFilesRoute
  '/lab': typeof LabRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/api/hono/$': typeof ApiHonoSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-files'
    | '/lab'
    | '/logs'
    | '/profile'
    | '/api/hono/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-files'
    | '/lab'
    | '/logs'
    | '/profile'
    | '/api/hono/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/case-files'
    | '/lab'
    | '/logs'
    | '/profile'
    | '/api/hono/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseFilesRoute: typeof CaseFilesRoute
  LabRoute: typeof LabRoute
  LogsRoute: typeof LogsRoute
  ProfileRoute: typeof ProfileRoute
  ApiHonoSplatRoute: typeof ApiHonoSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-files': {
      id: '/case-files'
      path: '/case-files'
      fullPath: '/case-files'
      preLoaderRoute: typeof CaseFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hono/$': {
      id: '/api/hono/$'
      path: '/api/hono/$'
      fullPath: '/api/hono/$'
      preLoaderRoute: typeof ApiHonoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseFilesRoute: CaseFilesRoute,
  LabRoute: LabRoute,
  LogsRoute: LogsRoute,
  ProfileRoute: ProfileRoute,
  ApiHonoSplatRoute: ApiHonoSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
